<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-white leading-tight">
Classroom For 
@foreach($teachers as $teacher)
{{$teacher->user->name}}
{{$teacher->user->school_id}}
@endforeach
        </h2>
    </x-slot>

    <div class="py-2">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-black-900 dark:black-100">
{{--
@foreach ($teachers as $school)
    <div>
        <h2>School ID: {{ $school->school_id }}</h2>
        <h3>Teacher: {{ $school->user->name }}</h3>
        
        @foreach ($school->classrooms as $classroom)
            <div>
                <p>Classroom ID: {{ $classroom->id }}</p>
                <p>Teacher ID (from pivot): {{ $classroom->pivot->teacher_id }}</p>
            </div>
        @endforeach
    </div>
@endforeach
--}}
     {{--$classroom--}}          
{{--$students
<select name="classroom_id" id="classroom_{{$student->id}}">
                @foreach($classrooms as $classroom)
                    <option value="{{ $classroom->id }}">{{ $classroom->name }}</option>
                @endforeach
            </select>
--}}

{{--$students--}}


ClassRoom Schedule: <BR>

@foreach($classsched as $clas)

[ID: {{$clas->id}}] Time : {{$clas->schedule_time}} {{$clas->name}}<BR>

@endforeach


{{--$classsched--}}


<BR>



@foreach($students as $student)
{{--$student--}}
 <form action="{{ route('admin.assign_student_to_classroom', ['student' => $student->id, 'classroom' => $classroom->id]) }}" method="POST">
        @csrf
        <input type="text" name="classroom_id" value="{{ $classroom->id }}">
        <input type="text" name="student_id" value="{{ $student->id }}">
        <input type="test" name="school_id" value="{{$teacher->user->school_id}}">
        <div>
            <span>[ {{$student->id}} ]</span>
            <span>{{$student->fname}} {{$student->lname}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Assign to Classroom</button>
    </form>
    <br>
@endforeach
      </div>
      
 <div class="p-6 text-black-900 dark:black-100">



<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="/img/classroom-layout-pair-up.jpg" usemap="#image-map">

<map name="image-map">
    <area target="" alt="teach" title="teach" href="teacher"        coords="24,142,100,228" shape="rect">
    <area target="" alt="student" title="student" href="student1"   coords="137,6,179,38" shape="rect">
    <area target="" alt="student" title="student" href="student2"   coords="137,43,179,76" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="216,9,265,41" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="215,44,264,80" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="296,12,345,46" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="298,49,343,83" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="135,111,181,140" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="134,149,179,179" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="219,113,264,146" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="219,150,263,182" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="299,110,348,146" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="299,150,346,183" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="130,202,178,233" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="133,236,176,272" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="214,203,264,237" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="215,241,262,274" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="297,208,348,244" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="293,247,349,280" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="128,291,180,323" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="126,328,180,361" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="211,293,260,328" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="212,332,258,363" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="294,295,340,330" shape="rect">
    <area target="" alt="student1" title="student1" href="student1" coords="296,333,337,361" shape="rect">
</map>
















 </div>
              
{{--$students--}}
            </div>
        </div>
    </div>
   
</x-app-layout>
